"""create overview table

Revision ID: f9bcd8b29501
Revises: bcc223e0b8c1
Create Date: 2020-11-25 05:21:56.344424

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f9bcd8b29501'
down_revision = 'bcc223e0b8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('overview', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('ratings', 'movie_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('ratings', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('ratings', 'movie_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_table('overviews')
    # ### end Alembic commands ###
